partner/pmp-misp-service/pom.xml
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/constant/MispIdPropertyConstant.java
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/controller/MispController.java
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/entity/Misp.java
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/exception/ErrorMessages.java
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/repository/MispRepository.java
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/service/MispIdGeneratorImpl.java
partner/pmp-misp-service/src/test/java/io/mosip/pmp/misp/test/service/MispIdServiceTest.java
partner/pmp-misp-service/src/test/resources/application.properties
partner/pmp-partner-service/src/main/java/io/mosip/pmp/partner/service/impl/PartnerServiceImpl.java

* misp id generator dependency has been removed from kernel.

misp id generator dependency has been removed from kernel.

---

partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/dto/MISPUpdateRequestDto.java
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/service/MISPManagementService.java
partner/pmp-misp-service/src/test/java/io/mosip/pmp/misp/test/controller/MispControllerTest.java
partner/pmp-misp-service/src/test/java/io/mosip/pmp/misp/test/service/MISPServiceTest.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/controller/PolicyManagementController.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/entity/AuthPolicyH.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/entity/PartnerPolicy.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/errorMessages/ErrorMessages.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/repository/AuthPolicyRepository.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/repository/PartnerPolicyRepository.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/service/PolicyManagementService.java
partner/pmp-policy-management-service/src/test/java/io/mosip/pmp/policy/test/controller/PolicyManagementControllerTest.java
partner/pmp-policy-management-service/src/test/java/io/mosip/pmp/policy/test/service/PolicyServiceTest.java

* Policy history added.
* Misc issues have been fixed.

MOSIP-7028

---

partner/pmp-policy-management-service/pom.xml
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/constant/PolicyCommonConstants.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/controller/PolicyManagementController.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/AllowedKycDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/DataShareDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/PolicyAttributesDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/PolicyCreateRequestDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/PolicyCreateResponseDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/PolicyDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/PolicyGroupCreateRequestDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/PolicyGroupCreateResponseDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/PolicyGroupUpdateRequestDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/PolicyResponseDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/PolicyStatusUpdateRequestDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/PolicyUpdateRequestDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/PolicyWithAuthPolicyDto.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/dto/RequestWrapper.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/entity/AuthPolicy.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/entity/AuthPolicyH.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/entity/PartnerPolicy.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/entity/PolicyGroup.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/errorMessages/ErrorMessages.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/repository/AuthPolicyRepository.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/service/PolicyManagementService.java
partner/pmp-policy-management-service/src/main/resources/application-local.properties
partner/pmp-policy-management-service/src/test/java/io/mosip/pmp/policy/test/controller/PolicyManagementControllerTest.java
partner/pmp-policy-management-service/src/test/java/io/mosip/pmp/policy/test/service/PolicyServiceTest.java
partner/pmp-policy-management-service/src/test/resources/application.properties

policies(auth/DataShare/credentialIssuance)

[MOSIP-8570]- policy manager supporting different types of

---

partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/config/ReqResFilter.java
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/controller/MispController.java
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/exception/ApiExceptionHandler.java
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/exception/MISPException.java
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/service/MISPManagementService.java
partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/utils/MispLogger.java
partner/pmp-partner-management-service/src/main/java/io/mosip/pmp/partnermanagement/service/impl/PartnerManagementServiceImpl.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/config/ReqResFilter.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/controller/PolicyManagementController.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/errorMessages/PolicyManagementServiceException.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/errorMessages/PolicyServiceLogger.java
partner/pmp-policy-management-service/src/main/java/io/mosip/pmp/policy/service/PolicyManagementService.java

Log change

---

partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/service/impl/RegisteredDeviceServiceImpl.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/regdevice/service/impl/RegRegisteredDeviceServiceImpl.java

This got missed while merging audit changes. So adding again.

Device digital id signing

---

partner/pmp-common/src/main/java/io/mosip/pmp/common/constant/Purpose.java
partner/pmp-common/src/main/java/io/mosip/pmp/common/dto/DeviceFilterValueDto.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/controller/DeviceDetailController.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/controller/FTPChipDetailController.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/controller/SecureBiometricInterfaceController.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/dto/ColumnCodeValue.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/dto/FTPChipDetailDto.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/dto/FTPSearchResponseDto.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/dto/FilterResponseCodeDto.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/dto/SecureBiometricInterfaceCreateDto.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/service/DeviceDetailService.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/service/FTPChipDetailService.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/service/SecureBiometricInterfaceService.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/service/impl/DeviceDetailServiceImpl.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/service/impl/FTPChipDetailServiceImpl.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/service/impl/SecureBiometricInterfaceServiceImpl.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/partner/controller/PartnerServiceController.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/partner/service/PartnerService.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/partner/service/impl/PartnerServiceImpl.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/regdevice/service/RegDeviceDetailService.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/regdevice/service/RegFTPChipDetailService.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/regdevice/service/RegSecureBiometricInterfaceService.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/regdevice/service/impl/RegDeviceDetailServiceImpl.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/regdevice/service/impl/RegFTPChipDetailServiceImpl.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/regdevice/service/impl/RegSecureBiometricInterfaceServiceImpl.java

Following api's has been added.
1. Device Type filter
2. Device Sub Type filter
3. FTM Details Search
4. Device Details filter
5. Partner filter

MOSIP-10775

---

partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/dto/DeviceDetailDto.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/dto/FTPChipDetailUpdateDto.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/dto/FTPSearchResponseDto.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/entity/FTPChipDetail.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/service/impl/DeviceDetailServiceImpl.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/authdevice/service/impl/FTPChipDetailServiceImpl.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/regdevice/entity/RegFTPChipDetail.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/regdevice/service/impl/RegDeviceDetailServiceImpl.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/regdevice/service/impl/RegFTPChipDetailServiceImpl.java

Changes column names to make it uniform

MOSIP-11461

---

partner/pmp-misp-service/Dockerfile
partner/pmp-partner-management-service/Dockerfile
partner/pmp-partner-service/Dockerfile
partner/pmp-policy-management-service/Dockerfile

As per security recommendations, the container should run without root privileges. Added and Enabled docker user to run the services with a non-root user.

Added/Enabled Docker user

---

partner/pmp-misp-service/src/main/java/io/mosip/pmp/misp/PmpMispApplication.java
partner/pmp-partner-service/src/main/java/io/mosip/pmp/regdevice/service/impl/RegRegisteredDeviceServiceImpl.java

Fixing build error. MISP service is going into CrashLoopBackOff state

Fixing build error.

---

partner/partner-management-service/src/main/java/io/mosip/pms/device/authdevice/service/impl/DeviceDetailServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/device/authdevice/service/impl/FTPChipDetailServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/device/authdevice/service/impl/RegisteredDeviceServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/device/authdevice/service/impl/SecureBiometricInterfaceServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/device/regdevice/service/impl/RegDeviceDetailServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/device/regdevice/service/impl/RegFTPChipDetailServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/device/regdevice/service/impl/RegRegisteredDeviceServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/device/regdevice/service/impl/RegSecureBiometricInterfaceServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/partner/manager/service/impl/PartnerManagementServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/partner/service/impl/PartnerServiceImpl.java
partner/partner-management-service/src/test/java/io/mosip/pms/test/partner/service/impl/PartnerServiceImplTest.java
partner/policy-management-service/src/main/java/io/mosip/pms/policy/service/PolicyManagementService.java

Db isDeleted falg made as not null. SO corresponding changes done in code.

Is Deleted made not null

---

.github/workflows/push_trigger.yml
partner/pom.xml

Revert "Added sonar cloud plugin and enabled sonar cloud analysis."

---

partner/partner-management-service/src/main/java/io/mosip/pms/partner/controller/PartnerServiceController.java

partner filter api access  role has been updated

role updation

---

partner/partner-management-service/src/main/java/io/mosip/pms/partner/service/impl/PartnerServiceImpl.java

From UI partner type code coming all in caps letters but actual data in table is camel case. So while validating, checking with ignore case

fix for partner registration from portal

---

partner/pmp-misp-service/Dockerfile
partner/pmp-partner-management-service/Dockerfile
partner/pmp-partner-service/Dockerfile
partner/pmp-policy-management-service/Dockerfile

added property -Dlog4j2.formatMsgNoLookups

updated pms

---

partner/partner-management-service/pom.xml
partner/pms-common/pom.xml
partner/policy-management-service/pom.xml
partner/policy-validator/pom.xml
partner/pom.xml

java.lang.ClassNotFoundException: com.fasterxml.jackson.module.afterburner.AfterburnerModule

Updated dependencies to resolve jackson error

---

partner/pom.xml

Reverts mosip/partner-management-services#307

Revert "MOSIP-17735 changing websub version for migration"

---

partner/pom.xml

Reverts mosip/partner-management-services#372

Revert "Revert "MOSIP-17735 changing websub version for migration""

---

db_release_scripts/mosip_pms/ddl/pms-secure_biometric_interface.sql
db_release_scripts/mosip_pms/ddl/pms-secure_biometric_interface_h.sql

Change: DB scripts have been modified.
'device_detail_id' column is not present in table but in comments column is present. Due to this scripts are failing.
Removed 'device_detail_id' column for comments section also.

[MOSIP-21074]Release scripts updated

---

apitest/src/main/resources/pms/ActivateDeactivatePartnerApiKey/ActivateDeactivatePartnerApiKey.yml
apitest/src/main/resources/pms/ApproveMappingKey/ApproveMappingKey.yml
apitest/src/main/resources/pms/CreatePartner/CreatePartner.yml
apitest/src/main/resources/pms/DeactivateOIDCClient/DeactivateOIDCClient.yml
apitest/src/main/resources/pms/DefinePolicy/DefinePolicy.yml
apitest/src/main/resources/pms/DefinePolicyGroup/DefinePolicyGroup.yml
apitest/src/main/resources/pms/GenerateApiKey/GenerateApiKey.yml

Added definePolicyGroup test cases

added definePolicyGroup test cases

---

apitest/pom.xml

DSD-6112 - updated the apitest commons version to 1.2.1

DSD-6112 - updated the apitest commons version to 1.2.1

---

.github/workflows/push-trigger.yml
apitest/Dockerfile
apitest/pom.xml

MOSIP-35671 - Merging java21 with develop

MOSIP-35671 - Merging java21 with develop

---

apitest/src/main/java/io/mosip/testrig/apirig/testrunner/MosipTestRunner.java
apitest/src/main/resources/config/keyManagerDataDeleteQueries.txt
apitest/src/main/resources/config/pmsDataDeleteQueries.txt

MOSIP-35671 -Merging java21 with develop

MOSIP-35671 -Merging java21 with develop

---

apitest/src/main/resources/pms/DeactivateOIDCClient/DeactivateOIDCClient.yml
apitest/src/main/resources/pms/GetAllActivePolicyGroups/GetAllActivePolicyGroups.yml
apitest/src/main/resources/pms/GetAllApiKeyForAuthPartner/GetAllApiKeyForAuthPartner.yml
apitest/src/main/resources/pms/GetAllApiKeyForAuthPartner2/GetAllApiKeyForAuthPartnernegativescenario.yml
apitest/src/main/resources/pms/GetAllApprovedAuthPartnerPolicy/GetAllApprovedAuthPartnerPolicy.yml
apitest/src/main/resources/pms/GetAllApprovedAuthPartnerPolicy/GetAllApprovedAuthPartnerPolicyNegativeScenarios.yml
apitest/src/main/resources/pms/GetAllApprovedPartnerId/GetAllApprovedPartnerId.yml
apitest/src/main/resources/pms/GetAllApprovedPartnerId/GetAllApprovedPartnerIdNegativeScenarios.yml
apitest/src/main/resources/pms/GetAllCertificate/GetAllCertificate.yml
apitest/src/main/resources/pms/GetAllCertificate/GetAllCertificateNegativeScenarios.yml
apitest/src/main/resources/pms/GetAllOidcClient/GetAllOidcClient.yml
apitest/src/main/resources/pms/GetAllOidcClient/GetAllOidcClientNegativeScenarios.yml
apitest/src/main/resources/pms/GetAllRequestedPolicy/GetAllRequestedPolicy.yml
apitest/src/main/resources/pms/GetAllRequestedPolicy/GetAllRequestedPolicyNegativeScenarios.yml
apitest/src/main/resources/pms/OIDCClient/OIDCClient.yml
apitest/src/main/resources/pms/OIDCClient/UpdateOIDCClient.yml
apitest/testNgXmlFiles/pmsApi.xml

Update the endpoint of the test cases . API endpoints that were developed in PMS_Release-1.3.0-DP.1

MOSIP-36023

---

partner/partner-management-service/src/main/java/io/mosip/pms/device/authdevice/service/impl/SecureBiometricInterfaceServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/partner/util/PartnerHelper.java

Reverts mosip/partner-management-services#909

Revert "MOSIP-36089: partner admin role bug fix."

---

api-test/src/main/java/io/mosip/testrig/apirig/testrunner/MosipTestRunner.java
api-test/src/main/resources/pms/ApproveMappingDeviceToSbi/ApproveMappingDeviceToSbi.hbs
api-test/src/main/resources/pms/ApproveMappingDeviceToSbi/ApproveMappingDeviceToSbi.yml
api-test/src/main/resources/pms/DeactivateDevice/DeactivateDevice.hbs
api-test/src/main/resources/pms/DeactivateDevice/DeactivateDevice.yml
api-test/src/main/resources/pms/DeactivateOIDCClient/DeactivateOIDCClient.yml
api-test/src/main/resources/pms/DeactivateSBIWithAssociatedDevices/DeactivateSBIWithAssociatedDevices.hbs
api-test/src/main/resources/pms/DeactivateSBIWithAssociatedDevices/DeactivateSBIWithAssociatedDevices.yml
api-test/src/main/resources/pms/FilterAPIs/DeviceSubTypeFilter/DeviceSubTypeFilter.hbs
api-test/src/main/resources/pms/FilterAPIs/DeviceSubTypeFilter/DeviceSubTypeFilter.yml
api-test/src/main/resources/pms/FilterAPIs/DeviceTypeFilter/DeviceTypeFilter.hbs
api-test/src/main/resources/pms/FilterAPIs/DeviceTypeFilter/DeviceTypeFilter.yml
api-test/src/main/resources/pms/GetAllDeviceListMappedWithSbi/GetAllDeviceListMappedWithSbi.hbs
api-test/src/main/resources/pms/GetConfiguration/GetConfiguration.yml
api-test/src/main/resources/pms/GetOriginalPartnerCertificates/GetOriginalPartnerCertificates.hbs
api-test/src/main/resources/pms/GetOriginalPartnerCertificates/GetOriginalPartnerCertificates.yml
api-test/src/main/resources/pms/GetUserConsent/GetUserConsent.yml
api-test/src/main/resources/pms/InactiveMappingDeviceToSbi/InactiveMappingDeviceToSbi.hbs
api-test/src/main/resources/pms/InactiveMappingDeviceToSbi/InactiveMappingDeviceToSbi.yml
api-test/src/main/resources/pms/OIDCClient/OIDCClient.yml
api-test/src/main/resources/pms/OIDCClient/UpdateOIDCClient.yml
api-test/src/main/resources/pms/partnerPolicyMapping/partnerPolicyMapping.yml
api-test/testNgXmlFiles/pmsApi.xml

MOSIP-35416 fix automation failure

MOSIP-35416 fix automation failure

---

api-test/src/main/java/io/mosip/testrig/apirig/testrunner/MosipTestRunner.java

MOSIP-36555 - Removed the OTPListener initializing and cleaned up

MOSIP-36555 - Removed the OTPListener initializing and cleaned up

---

api-test/src/main/java/io/mosip/testrig/apirig/testrunner/MosipTestRunner.java
api-test/src/main/java/io/mosip/testrig/apirig/testscripts/GetWithParam.java
api-test/src/main/resources/partner/MispLicense/GetMISPLicenseByMispID/GetMISPLicenseByMispID.yml
api-test/src/main/resources/partner/MispLicense/GetMISPLicenseByMispID/getMISPLicenseByMispIDResult.hbs
api-test/src/main/resources/partner/authPartner/UploadCertificate/UploadCertificate.yml

MOSIP-36275 - Fixed automation issue for Upload certificate api and get MISP License api

MOSIP-36275 - Fixed automation issue for Upload certificate api and get MISP License api

---

api-test/src/main/resources/pms/DeactivateDevice/DeactivateDeviceNegativeScenarios.yml
api-test/src/main/resources/pms/DeactivateFtm/DeactivateFtmNegativeScenarios.yml
api-test/src/main/resources/pms/DeactivateSBIWithAssociatedDevices/DeactivateSBIWithAssociatedDevicesNegativeScenarios.yml
api-test/src/main/resources/pms/GetAllActivePolicyGroups/GetAllActivePolicyGroups.yml
api-test/src/main/resources/pms/GetAllApiKeyForAuthPartner/GetAllApiKeyForAuthPartner.yml
api-test/src/main/resources/pms/GetAllApprovedAuthPartnerPolicy/GetAllApprovedAuthPartnerPolicyNegativeScenarios.yml
api-test/src/main/resources/pms/GetAllApprovedDeviceProviderIds/GetAllApprovedDeviceProviderIdsNegativeScenarios.yml
api-test/src/main/resources/pms/GetAllApprovedFtmProvider/GetAllApprovedFtmProviderNegativeScenarios.yml
api-test/src/main/resources/pms/GetAllApprovedPartnerId/GetAllApprovedPartnerIdNegativeScenarios.yml
api-test/src/main/resources/pms/GetAllCertificate/GetAllCertificate.yml
api-test/src/main/resources/pms/GetAllDeviceListMappedWithSbi/GetAllDeviceListMappedWithSbiNegativeScenarios.yml
api-test/src/main/resources/pms/GetAllOidcClient/GetAllOidcClientNegativeScenarios.yml
api-test/src/main/resources/pms/GetAllRequestedPolicy/GetAllRequestedPolicyNegativeScenarios.yml
api-test/src/main/resources/pms/GetListAllFTMChip/GetListAllFTMChipNegativeScenarios.yml
api-test/src/main/resources/pms/GetOriginalFtmCertifacte/GetOriginalFtmCertifacteNegativeScenarios.yml
api-test/src/main/resources/pms/OIDCClient/OIDCClient.yml
api-test/src/main/resources/pms/PublishPolicy/PublishPolicy.yml
api-test/src/main/resources/pms/SaveUserConsent/SaveUserConsent.yml
api-test/src/main/resources/pms/VerifyPartnersEmail/VerifyPartnersEmail.yml

MOSIP-37889 - updated the user for negative testcases

MOSIP-37889 - updated the user for negative testcases

---

api-test/README.md

MOSIP-34532 - Updated the ReadMe file

MOSIP-34532 - Updated the ReadMe file

---

api-test/src/main/java/io/mosip/testrig/apirig/testscripts/GetWithParam.java
api-test/src/main/java/io/mosip/testrig/apirig/testscripts/PostWithOnlyPathParam.java
api-test/src/main/java/io/mosip/testrig/apirig/testscripts/SimplePatch.java
api-test/src/main/java/io/mosip/testrig/apirig/testscripts/SimplePost.java
api-test/src/main/java/io/mosip/testrig/apirig/testscripts/SimplePostForAutoGenId.java
api-test/src/main/java/io/mosip/testrig/apirig/testscripts/SimplePostWithoutBody.java
api-test/src/main/java/io/mosip/testrig/apirig/testscripts/SimplePut.java

- Moved module-specific code from commons.
- Removed the module-specific code reference to commons

MOSIP-35404

---

partner/partner-management-service/src/main/java/io/mosip/pms/device/authdevice/service/impl/DeviceDetailServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/device/authdevice/service/impl/SecureBiometricInterfaceServiceImpl.java
partner/partner-management-service/src/main/java/io/mosip/pms/partner/util/PartnerHelper.java

Reverts mosip/partner-management-services#1088

Revert "MOSIP-38450: Removed SBI id belongs to the user for Partner Admin"

---

api-test/testNgXmlFiles/pmsSuite.xml

Reverts mosip/partner-management-services#1116

Revert "MOSIP-39071 - Fixed the automation failures"

---

api-test/src/main/resources/pms/DefinePolicy/DefinePolicy.yml

MOSIP-39071 - Fix automation issues

MOSIP-39071 - Fix automation issues

---

api-test/src/main/resources/config/partnerRevampDataDeleteQueries.txt
api-test/src/main/resources/pms/DefinePolicy/DefinePolicy.yml

MOSIP-39071 - Added db queries

MOSIP-39071 - Added db queries

---

partner/partner-management-service/src/main/java/io/mosip/pms/device/authdevice/repository/DeviceDetailRepository.java

…ranch of partner-management-services repo

MOSIP-39822: Fixed automation failure for deactivating SBI

---

api-test/README.md

MOSIP-40434 - Updated the readme file

MOSIP-40434 - Updated the readme file

---

api-test/pom.xml

Changed POM version to 1.2.2.1-SNAPSHOT for release

Changed POM version to 1.2.2.1-SNAPSHOT for release

---

api-test/src/main/resources/pms/DismissNotification/DismissNotificationNegativeScenarios.yml
api-test/src/main/resources/pms/GetAllDeviceListMappedWithSbi/GetAllDeviceListMappedWithSbiNegativeScenarios.yml
api-test/src/main/resources/pms/GetAllNotifications/GetAllNotifications.yml
api-test/src/main/resources/pms/GetRootIntermediateExpiringCertificate/GetRootIntermediateExpiringCertificate.hbs
api-test/src/main/resources/pms/GetRootIntermediateExpiringCertificate/GetRootIntermediateExpiringCertificate.yml
api-test/src/main/resources/pms/GetRootIntermediateExpiringCertificate/GetRootIntermediateExpiringCertificateNegativeScenarios.yml
api-test/src/main/resources/pms/GetRootIntermediateExpiringCertificate/GetRootIntermediateExpiringCertificateResult.hbs
api-test/src/main/resources/pms/RejectMappingDeviceToSbi/RejectMappingDeviceToSbiNegativeScenarios.yml
api-test/testNgXmlFiles/pmsSuite.xml

*Pushed the latest API code to release branch from develop*

MOSIP-41289 - Pushed the latest API code to release branch from develop

---

api-test/src/main/resources/config/pmsRevamp.properties

Removed values from properties

MOSIP-41445 - Removed values from properties
